Vagrant.configure("2") do |config|
    config.vm.define "web" do |node|
        node.vm.box = "ubuntu/trusty64"
        node.vm.hostname = "web"
        node.vm.network :private_network, ip: "192.168.56.101"
        node.vm.network "forwarded_port", guest: 80, host: "8080"
        node.vm.provider "virtualbox" do |vb|
          vb.memory = "256"
        end
    end

    config.vm.provision "shell" do |s|
      ssh_pub_key = File.readlines("id_rsa.pub").first.strip
      s.inline = <<-SHELL
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      SHELL
    end
end